Repository Taewan-P/gpt_mobile, pull requests merged in 2024-07, with the labels that each got.

#13 Support customizing temperature, top p (Nucleus Sampling), and system prompt
  README.md
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/datastore/SettingDataSource.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/datastore/SettingDataSourceImpl.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/dto/Platform.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/dto/anthropic/request/MessageRequest.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/SettingRepositoryImpl.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/common/SettingItem.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/PlatformSettingDialogs.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/PlatformSettingScreen.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/SettingScreen.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/SettingViewModel.kt
  app/src/main/res/drawable/ic_chart.xml
  app/src/main/res/drawable/ic_instructions.xml
  app/src/main/res/drawable/ic_temperature.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#14 Fix system prompt state mismatch when dialog is canceled
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/PlatformSettingDialogs.kt
Labels: bug

#15 Add about page & license page
  README.md
  app/build.gradle.kts
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/SettingRepositoryImpl.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/common/NavigationGraph.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/common/Route.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/AboutScreen.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/LicenseScreen.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/SettingScreen.kt
  app/src/main/res/drawable/ic_f_droid.xml
  app/src/main/res/drawable/ic_feedback.xml
  app/src/main/res/drawable/ic_github.xml
  app/src/main/res/drawable/ic_info.xml
  app/src/main/res/drawable/ic_license.xml
  app/src/main/res/drawable/ic_play_store.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values/strings.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: enhancement

#17 Remove timestamp to support reproducible builds
  app/build.gradle.kts
Labels: bug

#24 Add Simplified Chinese translation
  app/src/main/res/values-zh-rCN/strings.xml
Labels: translation
