Repository Taewan-P/gpt_mobile, pull requests merged in 2024-10, with the labels that each got.

#48 Add GPT-4o mini support
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/ModelConstants.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/util/MapStringResources.kt
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#49 Navigate to new chat directly if only one platform is enabled
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/home/HomeScreen.kt
Labels: enhancement

#64 Update App Links
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setting/AboutScreen.kt
  app/src/main/res/drawable/ic_bug_report.xml
  app/src/main/res/values-ko-rKR/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-zh-rCN/strings.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#65 Prevent multiple line title
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt
Labels: bug

#66 Add scroll to bottom functionality
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/chat/ChatScreen.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/chat/ChatViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#76 Fix disappearing chat when 2 or more chats are retrying
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/common/TokenInputField.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/chat/ChatViewModel.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/home/HomeScreen.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/util/StateFlowExtensions.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: bug

#77 Switch markdown library
  app/build.gradle.kts
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/chat/ChatBubble.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: enhancement

#78 Add copy message chip to user message
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/chat/ChatBubble.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/chat/ChatScreen.kt
Labels: enhancement

#82 Fix going to intro screen when Ollama is only initially selected and used
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/main/MainViewModel.kt
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/presentation/ui/setup/SetupViewModel.kt
Labels: bug

#85 Correct and Update Chinese Simplified translation
  app/src/main/res/values-zh-rCN/strings.xml
Labels: translation

#91 Fix Ollama assistant message not being gathered when sent to the API
  .idea/runConfigurations.xml
  app/src/main/kotlin/dev/chungjungsoo/gptmobile/data/repository/ChatRepositoryImpl.kt
Labels: bug
